on: [push, pull_request]

jobs:
  configured-deps:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        php: ['8.3']
    steps:
      - name: Checkout PhpRedis
        uses: actions/checkout@v4

      - name: Install liblzf
        run: |
          git clone --depth=1 https://github.com/nemequ/liblzf.git
          cd liblzf
          autoreconf -vi
          CFLAGS=-fPIC ./configure --prefix="$GITHUB_WORKSPACE/liblzf"
          make install

      - name: Install liblz4
        run: |
          git clone -b v1.9.4 --depth=1 https://github.com/lz4/lz4
          cd lz4/lib
          PREFIX="$GITHUB_WORKSPACE/liblz4" make install

      - name: Install libzstd
        run: |
          git clone -b v1.5.5 --depth=1 https://github.com/facebook/zstd
          cd zstd
          PREFIX="$GITHUB_WORKSPACE/libzstd" make install

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, igbinary, msgpack, :redis
          coverage: none
          tools: none

      - name: Configure and build PhpRedis with distinct dep paths
        run: |
          phpize
          ./configure \
            --enable-redis-lz4 \
            --with-liblz4="$GITHUB_WORKSPACE/liblz4" \
            --enable-redis-lzf \
            --with-liblzf="$GITHUB_WORKSPACE/liblzf" \
            --enable-redis-zstd \
            --with-libzstd="$GITHUB_WORKSPACE/libzstd"
          sudo make -j"$(nproc)"

      - name: Make sure we're linking against specific liblz4
        run: |
          grep "INCLUDES.*$GITHUB_WORKSPACE/liblz4" Makefile
          grep "REDIS_SHARED_LIBADD.*-L$GITHUB_WORKSPACE/liblz4" Makefile

      - name: Make sure we're linking against specific liblzf
        run: |
          grep "INCLUDES.*$GITHUB_WORKSPACE/liblzf" Makefile
          grep "REDIS_SHARED_LIBADD.*-L$GITHUB_WORKSPACE/liblzf" Makefile

      - name: Make sure we're linking against specific libzstd
        run: |
          grep "INCLUDES.*$GITHUB_WORKSPACE/libzstd" Makefile
          grep "REDIS_SHARED_LIBADD.*-L$GITHUB_WORKSPACE/libzstd" Makefile


  windows:
    runs-on: windows-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4']
        ts: [nts, ts]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install PHP ${{ matrix.php }}
        uses: php/setup-php-sdk@v0.10
        id: setup-php-sdk
        with:
          version: ${{ matrix.php }}
          arch: x64
          ts: ${{matrix.ts}}
          cache: true
      - name: Install dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{steps.setup-php-sdk.outputs.toolset}}
      - name: Build phpredis
        run: |
          phpize
          ./configure --enable-redis --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}
          nmake
      - name: package
        run: |
          md binaries
          copy LICENSE binaries
          Get-ChildItem -Recurse -Filter "php_redis.dll" | ForEach-Object {Copy-Item -Path $_.FullName -Destination "binaries"}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: redis-${{matrix.php}}-x64-${{matrix.ts}}
          path: binaries
